apiVersion: v1
  Search Google or type a URL


kind: Pod
metadata:
  labels:
    run: httpd-pod
  name: httpd-pod
spec:
  containers:
    - image: httpd:latest
      name: httpd-container
      resources:
        requests:
          memory: "15Mi"
          cpu: 1
        limits:
          memory: "20Mi"
          cpu: 2