apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-xfusion
  namespace: haproxy-controller-xfusion
  labels:
    run: ingress-default-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ingress-default-backend
  template:
    metadata:
      labels:
        run: ingress-default-backend
    spec:
      containers:
        - image: gcr.io/google_containers/defaultbackend:1.0
          name: backend-container-xfusion
          ports:
            - containerPort: 8080
