apiVersion: v1
kind: Service
metadata:
  name: service-backend-xfusion
  namespace: haproxy-controller-xfusion
  labels:
    run: ingress-default-backend
spec:
  ports:
    - name: port-backend
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: ingress-default-backend