apiVersion: v1
kind: Service
metadata:
  labels:
    app: tomcat
  name: tomcat-service-devops
  namespace: tomcat-namespace-devops
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32227
  selector:
    app: tomcat
  type: NodePort