apiVersion: v1
kind: Service
metadata:
  labels:
    run: jekyll-pod-devops
  name: jekyll-service-devops
  namespace: jekyll-namespace-devops
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 4000
      nodePort: 31181
  selector:
    run: jekyll-pod-devops
  type: NodePort
status:
  loadBalancer: {}