apiVersion: v1
kind: Service
metadata:
  labels:
    app: result-deployment
  name: result-service
  namespace: vote
spec:
  ports:
    - port: 5001
      protocol: TCP
      targetPort: 80
      nodePort: 31001
  selector:
    app: result-deployment
  type: NodePort