apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote-deployment
  name: vote-deployment
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-deployment
  template:
    metadata:
      labels:
        app: vote-deployment
    spec:
      containers:
        - image: kodekloud/examplevotingapp_vote:before
          name: vote
          ports:
            - containerPort: 80