apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd_app_nautilus
  name: httpd-service-nautilus
  namespace: httpd-namespace-nautilus
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30004
  selector:
    app: httpd_app_nautilus
  type: NodePort