apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd_app_nautilus
  name: httpd-deployment-nautilus
  namespace: httpd-namespace-nautilus
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd_app_nautilus
  template:
    metadata:
      labels:
        app: httpd_app_nautilus
    spec:
      containers:
        - image: httpd:latest
          name: httpd-container-nautilus