apiVersion: v1
kind: Service
metadata:
  labels:
    app: nagios-deployment
  name: nagios-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30008
  selector:
    app: nagios-deployment
  type: NodePort