apiVersion: v1
kind: Pod
metadata:
  name: nginx-phpfpm
spec:
  containers:
    - image: php:7.2-fpm
      name: php-fpm-container
      volumeMounts:
        - mountPath: /var/www/html
          name: shared-files
    - image: nginx:latest
      name: nginx-container
      volumeMounts:
        # Before:
        # - mountPath: /usr/share/nginx/html
        #   name: shared-files
        # After:
        - mountPath: /var/www/html
          name: shared-files
        #
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config-volume
          subPath: nginx.conf
  volumes:
    - emptyDir: {}
      name: shared-files
    - configMap:
        defaultMode: 420
        name: nginx-config
      name: nginx-config-volume